### ISSUE TITLE
Modal not preventing clicks on background.

### ISSUE THREAD

**Issue by MateuszStudiosCompany** [jpolgesek/zseilplan-website#2]
# About
You can use interface outsite of modal.
# How to reproduce
1. Open settings (or any other modal).
2. Click on blured settings button again (or any other button).
# What happens
Settings will open again on top of existing one.
# What should happen
Settings (or any blured buttons) should not be active when modal is open.

**Comment by jpolgesek** [comment]
Wow! Amazing find. Going to fix it asap.

**Comment by jpolgesek** [comment]
Should be fixed in [fix_issue_1_modal_disable_bg_buttons](https://github.com/jpolgesek/zseilplan-website/tree/fix_issue_1_modal_disable_bg_buttons) branch.

**Comment by jpolgesek** [comment]
@MateuszStudiosCompany can you confirm that this bug is gone now?

**Comment by MateuszStudiosCompany** [comment]
@jpolgesek Confirm!

**Comment by jpolgesek** [comment]
Okay, merging to develop
